/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pro.elab.git;

/**
 *
 * @author eugine
 */
public class FormGetTag extends java.awt.Dialog {

    String label = null;
    String projectDir = null;
    int gitMode = 0;
    gitFlow hf;

    /**
     * Creates new form FormGetTag
     */

    public FormGetTag(java.awt.Frame parent, boolean modal, String pDir, int mode) {
        super(parent, modal);
        initComponents();
        gitMode = mode;
        projectDir = pDir;
        hf = new gitFlow(projectDir);
        if (!hf.isFlowProject()) {
            closeDialog(null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                checkProject(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(FormGetTag.class, "FormGetTag.jLabel1.text")); // NOI18N
        add(jLabel1, java.awt.BorderLayout.NORTH);

        jTextField1.setText(org.openide.util.NbBundle.getMessage(FormGetTag.class, "FormGetTag.jTextField1.text")); // NOI18N
        add(jTextField1, java.awt.BorderLayout.CENTER);

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(FormGetTag.class, "FormGetTag.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        label = jTextField1.getText();
        switch (gitMode) {
            case 1: {
                hf.featureStart(label);
                break;
            }
            case 2: {
                hf.releaseStart(label);
                break;
            }
            default: {
                //
            }
        }
        closeDialog(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void checkProject(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_checkProject
        // TODO add your handling code here:
        if (!hf.isFlowProject()) {
            closeDialog(evt);
        }
    }//GEN-LAST:event_checkProject

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
